#!/bin/fish

if not string match -q '*arch*' (uname -r)

    echo 'This is not arch linux.'

    return 1

end

if not type -q checkupdates
    or not type -q paru

    echo 'Both checkupdates and paru must be installed.'

    return 1

end

set updates (checkupdates)

if test (count $updates) = 0

    echo "No updates are available."

    return

else

    set n 0

    for u in $updates

        set n (math $n + 1)

        printf "%4u) %s\n" $n $u

    end

end

# echo "$updates"

read -n 1 -P "Type 'y' to install updates: " yes

if string match -q y $yes

    doas sh -c 'paru --noconfirm -Syu && shutdown now'

end
